#!/usr/bin/env/python
import os

import click

import ljon.build
import ljon.server

@click.command()
@click.option('--root', default='.', help='Path to the the project')
@click.option('--server', is_flag=True,
              help='Run an HTTP server for the project')
@click.option('--host', default='0.0.0.0',
              help='The host for the HTTP server')
@click.option('--port', default=5657,
              help='The port for the HTTP server')
def build(root, server, host, port):
    ljon.build(root)

    if server:
        server = ljon.server.Server(host, port)
        server.start()


if __name__ == '__main__':
    build()
